ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB*

USER_LIB_PATH += /home/$(USER)/Arduino/libraries
ARDUINO_LIBS += ros_lib
ARDUINO_LIBS += sensors
ARDUINO_LIBS += battery
ARDUINO_LIBS += encoders
ARDUINO_LIBS += motors_pwm 

BOARD_TAG = mega2560 

include /usr/share/arduino/Arduino.mk

